name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install --force

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git config --global user.name 'sandeep-chennupati'
        git config --global user.email 'sandeep.chennupati@teladochealth.com'
        git remote set-url origin https://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@github.com/sandeep-chennupati/my-app
        npm run deploy
      # env:
      #   user_name: 'sandeep-chennupati'
      #   user_email: 'sandeep.chennupati@teladochealth.com'
      #   github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
      #   repository: 'sandeep-chennupati/my-app'